spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:D:/monitor/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
    ship:
      jdbc-url: jdbc:sqlite:D:/monitor/resources/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:D:/monitor/resources/waterway.db
      driver-class-name: org.sqlite.JDBC
    map:
      jdbc-url: jdbc:sqlite:D:/monitor/resources/map.db
      driver-class-name: org.sqlite.JDBC
    sensor:
      jdbc-url: jdbc:sqlite:E:/Graduate/graduate-1/workspace/water_data/codes/Instrument/sensor_data.db
      driver-class-name: org.sqlite.JDBC
    reception:
      jdbc-url: jdbc:sqlite:E:/Graduate/graduate-1/workspace/station-transfer/reception.db
      driver-class-name: org.sqlite.JDBC
    waterdata:
      jdbc-url: jdbc:sqlite:E:/Graduate/graduate-1/workspace/monitor/StormPerdiction/data/waterdata/waterdata.db
      driver-class-name: org.sqlite.JDBC

#D:/UyNauhL/Assignments/monitor_data/monitor

# 记得手动修改pythonDir
pythonDir: D:/monitor/pythonDir/
baseDir: D:/monitor/resources/raw/
avatarDir: D:/monitor/resources/avatar/
tempDir: D:/monitor/temp/
visualDir: D:/monitor/resources/visual/
pgPath: D:/Program Files/PostgreSQL/18/bin
mapDir: D:/monitor/resources/map/
resourceDir: D:/monitor/resources/
analysisDir: D:/monitor/resources/analysis/
analysisParameterDir: D:/monitor/resources/analysisParameter/
projectDir: D:/monitor/project/

meteorologyUrl: https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/

waterLevelAddress: http://localhost:8700/mock/waterLevel
#  http://172.21.212.116:9999

AISUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?from={0}&name={1}&size={2}

fileViewUrl:
  http://localhost:8012/fileUpload

LocalMap:
  http://127.0.0.1:3000