spring:
  datasource:
    default:
      jdbc-url: jdbc:sqlite:/usr/local/resource/main.db
      driver-class-name: org.sqlite.JDBC
    shp:
      jdbc-url: jdbc:postgresql://localhost:5432/shp_dataset?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
    ship:
      jdbc-url: jdbc:sqlite:/usr/local/resource/monitor_resource/ais.db
      driver-class-name: org.sqlite.JDBC
    waterway:
      jdbc-url: jdbc:sqlite:/usr/local/resource/monitor_resource/waterway.db
      driver-class-name: org.sqlite.JDBC
    map:
      jdbc-url: jdbc:sqlite:/usr/local/resource/monitor_resource/map.db
      driver-class-name: org.sqlite.JDBC

#D:/UyNauhL/Assignments/monitor_data/monitor

#pythonDir: "/usr/local/resource/monitor_pythonDir/"
#pythonDir: "E:/monitor/pythonDir/"
baseDir: /usr/local/resource/monitor_resource/raw/
avatarDir: /usr/local/resource/monitor_resource/avatar/
tempDir: /usr/local/resource/monitor_temp/
visualDir: /usr/local/resource/monitor_resource/visual/
pgPath: /usr/pgsql-13/bin/
mapDir:  /usr/local/resource/monitor_resource/map/
resourceDir: /usr/local/resource/monitor_resource/
analysisDir: /usr/local/resource/monitor_resource/analysis/
analysisParameterDir: /usr/local/resource/monitor_resource/analysisParameter/
projectDir: /usr/local/resource/monitor_project/

meteorologyUrl: https://weather.cma.cn/api/map/alarm
meteorologyPngUrl:
  http://data.cma.cn/dataGis/static/ultra/img/gis/disasterWarning/

waterLevelAddress:
  http://172.17.0.1:7777

AISUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?left={0}&bottom={1}&right={2}&top={3}
AISListUrl:
  https://www.cjienc.cn/rest/es/getBoxShips?from={0}&name={1}&size={2}

fileViewUrl:
  http://localhost:8012/fileUpload

LocalMap:
  http://172.17.0.1:3000